blank_issues_enabled: true
contact_links:  
  - name: General Question
    url: https://github.com/microsoft/winget-cli-restsource/discussions/new
    about: Have a question on something? Start a new discussion thread.
  - name: Review open issues
    url: https://github.com/microsoft/winget-cli-restsource/issues
    about: Please check if your issue or a similar issue has already been submitted