# Copyright (c) Microsoft Corporation. All rights reserved
# CI pipeline for winget-cli-restsource

trigger: none
pr: none

jobs:
- job: 'BuildTestPublish'
  displayName: 'Build, Publish & Test'
  timeoutInMinutes: 60
  pool:
    vmImage: windows-latest
    demands:
    - msbuild
    - visualstudio
  variables:
    BuildConfiguration: 'release'
    BuildPlatform: 'Any CPU'

  steps:
  # Restore and Build
  - template: templates/restore-build-sign-publish-test.yml

  # Run Compliance checks
  - template: templates/compliance.yml
