# Copyright (c) Microsoft Corporation. All rights reserved
# CI pipeline for winget-cli-restsource

# Standard Triggers
trigger: none

# PR triggers
pr:
  branches:
    include:
    - main
  paths:
    include:
    - pipelines/*
    - src/*

# TODO: The forked pr builds need to have the same permission as non-forked ones to access
#       project's internal nuget feed. Remove DisablePipelineConfigDetector variable when
#       a long term fix is available.
variables:
- name: DisablePipelineConfigDetector
  value: true

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling

    stages:
    - stage: __default
      jobs:
      - job: 'BuildPublishTest'
        displayName: 'Build Publish & Tests'
        timeoutInMinutes: 60
        variables:
        - name: BuildConfiguration
          value: 'release'
        - name: BuildPlatform
          value: 'Any CPU'

        steps:
        # Restore and Build
        - template: pipelines/templates/restore-build-publish-test.yml@self

        templateContext:
          outputs:
          # Publish ARM Templates
          - output: pipelineArtifact
            displayName: 'Publish Artifact: WinGet.RestSource-WinGet.Restsource.Infrastructure'
            targetPath: $(Build.ArtifactStagingDirectory)\WinGet.Restsource.Infrastructure
            artifactName: WinGet.RestSource-WinGet.Restsource.Infrastructure

          # Publish scripts
          - output: pipelineArtifact
            displayName: 'Publish Artifact: WinGet.RestSource-ReleaseScripts'
            targetPath: $(Build.ArtifactStagingDirectory)\ReleaseScripts
            artifactName: WinGet.RestSource-ReleaseScripts

          # Publish Rest Function App
          - output: pipelineArtifact
            displayName: 'Publish Artifact: WinGet.RestSource-WinGet.RestSource.Functions'
            targetPath: $(Build.ArtifactStagingDirectory)\WinGet.RestSource.Functions
            artifactName: WinGet.RestSource-WinGet.RestSource.Functions

          # Publish Rest Function App as an artifact 
          - output: pipelineArtifact
            displayName: 'Publish Artifact: WinGet.RestSource-WinGet.RestSource.IntegrationTest'
            targetPath: $(Build.ArtifactStagingDirectory)\WinGet.RestSource.IntegrationTest
            artifactName: WinGet.RestSource-WinGet.RestSource.IntegrationTest

          # Publish Powershell Module
          - output: pipelineArtifact
            displayName: 'Publish Artifact: WinGet.RestSource-Winget.PowerShell.Source'
            targetPath: '$(Build.ArtifactStagingDirectory)\Winget.PowerShell.Source'
            artifactName: 'WinGet.RestSource-Winget.PowerShell.Source'
