# Copyright (c) Microsoft Corporation. All rights reserved
# CI/PR pipeline for winget-cli-restsource

# Commit triggers
trigger:
- main

# PR triggers
pr:
  branches:
    include:
    - main
  paths:
    include:
    - pipelines/*
    - src/*

jobs:
- job: 'BuildTestPublish'
  displayName: 'Build, Publish & Test'
  timeoutInMinutes: 60
  pool:
    vmImage: windows-latest
    demands:
    - msbuild
    - visualstudio
  variables:
    BuildConfiguration: 'release'
    BuildPlatform: 'Any CPU'

  steps:
  # Restore and Build
  - template: templates/restore-build-publish-test.yml