# Copyright (c) Microsoft Corporation. All rights reserved
# CI pipeline for winget-cli-restsource

# Standard Triggers
trigger: none

# PR triggers
pr:
  branches:
    include:
    - main
  paths:
    include:
    - pipelines/*
    - src/*

# TODO: The forked pr builds need to have the same permission as non-forked ones to access
#       project's internal nuget feed. Remove DisablePipelineConfigDetector variable when
#       a long term fix is available.
variables:
- name: DisablePipelineConfigDetector
  value: true

jobs:
- job: 'BuildPublishTest'
  displayName: 'Build Publish & Tests'
  timeoutInMinutes: 60
  pool:
    name: 'Azure Pipelines'
    vmImage: windows-latest
    demands:
    - msbuild
    - visualstudio
  variables:
    BuildConfiguration: 'release'
    BuildPlatform: 'Any CPU'

  steps:
  # Restore and Build
  - template: templates/restore-build-publish-test.yml

# Static Analysis Job
- job: 'StaticAnalysis'
  displayName: 'Static Analysis'
  timeoutInMinutes: 60
  pool:
    name: 'Azure Pipelines'
    vmImage: windows-latest
    demands:
    - msbuild
    - visualstudio

  steps:
  # Analysis
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'Run CredScan'
    inputs:
      toolMajorVersion: V2
      debugMode: false

  # Publish SDT Logs
  - template: templates/copy-and-publish.yml
    parameters:
      name: StaticAnalysisLogs
      source: '$(Agent.BuildDirectory)\_sdt\logs'

  # SDT Post Analysis
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
    displayName: 'Post Analysis'
    inputs:
      CredScan: true
