# Copyright (c) Microsoft Corporation. All rights reserved
# CI pipeline for winget-cli-restsource

# Branches that trigger a build on commit
trigger:
- master

# PR triggers
pr:
  branches:
    include:
    - master
  paths:
    include:
    - pipelines/*
    - src/*

jobs:
- job: 'BuildTestPublish'
  displayName: 'Build, Publish & Test'
  timeoutInMinutes: 60
  pool:
    vmImage: windows-2019
    demands:
    - msbuild
    - visualstudio
  variables:
    BuildConfiguration: 'release'
    BuildPlatform: 'Any CPU'

  steps:
  # Restore and Build
  - template: templates/restore-build-publish-test.yml