# Copyright (c) Microsoft Corporation. All rights reserved
# CI pipeline for winget-cli-restsource

# Branches that trigger a build on commit
trigger:
- main

jobs:
- job: 'BuildTestPublish'
  displayName: 'Build Test & Publish'
  timeoutInMinutes: 60
  pool:
    name: 'Azure Pipelines'
    vmImage: windows-latest
    demands:
    - msbuild
    - visualstudio
  variables:
    BuildConfiguration: 'release'
    BuildPlatform: 'Any CPU'

  steps:
  # Restore and Build
  - template: templates/restore-build-publish-test.yml

  # Build Analysis - Binary Analysis (must run after build is complete on agent performing build)
  - template: templates/binSkim.yml
    parameters:
      name: winget-pkgs-restsource.BinSkim.ArtifactStagingDirectory
      binaries: "$(Build.ArtifactStagingDirectory)"
  
  # Publish SDT Logs
  - template: templates/copy-and-publish.yml
    parameters:
      name: StaticAnalysisLogs
      source: '$(Agent.BuildDirectory)\_sdt\logs'
  
  # SDT Post Analysis
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
    displayName: 'Post Analysis'
    inputs:
      BinSkim: true

# Static Analysis Job
- job: 'StaticAnalysis'
  displayName: 'Static Analysis'
  timeoutInMinutes: 120
  pool:
    name: 'Azure Pipelines'
    vmImage: windows-latest
    demands:
    - msbuild
    - visualstudio

  steps:
  # Analysis
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'Run CredScan'
    inputs:
      toolMajorVersion: V2
      debugMode: false

  # Semmle Requires Restore on Agent
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\NuGet.config'
      restoreDirectory: '$(Build.SourcesDirectory)\src\packages'

  - task: securedevelopmentteam.vss-secure-development-tools.build-task-semmle.Semmle@0
    displayName: 'Run Semmle'
    inputs:
      cleanupBuildCommands: '"%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" $(Build.SourcesDirectory)\src\WinGet.RestSource.sln /t:Clean'
      buildCommands: '"%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" $(Build.SourcesDirectory)\src\WinGet.RestSource.sln'

  # Publish SDT Logs
  - template: templates/copy-and-publish.yml
    parameters:
      name: StaticAnalysisLogs
      source: '$(Agent.BuildDirectory)\_sdt\logs'

  # SDT Post Analysis
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
    displayName: 'Post Analysis'
    inputs:
      CredScan: true
      Semmle: true
      $testBinaryPath: 

  # Code Inspector
  - task: CodeInspector@2
    inputs:
      ProductId: 'd2ca06e4-302f-4a16-99e5-27e39570d352'
